Functions
=========
A function is like a mini-program within a program. Type this program into the file editor and save it as helloFunc.py:

➊ def hello():
➋     print('Howdy!')
       print('Howdy!!!')
       print('Hello there.')
➌ hello()
   hello()
   hello()

The first line is a def statement ➊, which defines a function named hello(). The code in the block that follows the def 
statement ➋ is the body of the function. This code is executed when the function is called, not when the function is first 
defined.The hello() lines after the function ➌ are function calls. In code, a function call is just the function’s name 
followed by parentheses, possibly with some number of arguments in between the parentheses. When you run this program, the 
output looks like this:

Howdy!
Howdy!!!
Hello there.
Howdy!
Howdy!!!
Hello there.
Howdy!
Howdy!!!
Hello there.
def Statements with Parameters
-----------------------------
When you call the print() or len() function, you pass in values, called arguments in this context, by typing them between the 
parentheses.Type this example into the file editor and save it as helloFunc2.py:

➊ def hello(name):
➋     print('Hello ' + name)

➌ hello('Alice')
  hello('Bob')
When you run this program, the output looks like this:

Hello Alice
Hello Bob
Return Values and return Statements
-----------------------------------
A return statement consists of the following:
*The return keyword
*The value or expression that the function should return
Type this code into the file editor and save it as magic8Ball.py:

➊ import random
➋ def getAnswer(answerNumber):
➌     if answerNumber == 1:
           return 'It is certain'
       elif answerNumber == 2:
           return 'It is decidedly so'
       elif answerNumber == 3:
           return 'Yes'
       elif answerNumber == 4:
           return 'Reply hazy try again'
       elif answerNumber == 5:
           return 'Ask again later'
       elif answerNumber == 6:
           return 'Concentrate and ask again'
       elif answerNumber == 7:
           return 'My reply is no'
       elif answerNumber == 8:
           return 'Outlook not so good'
       elif answerNumber == 9:
           return 'Very doubtful'

➍ r = random.randint(1, 9)
➎ fortune = getAnswer(r)
➏ print(fortune)
Note that since you can pass return values as an argument to another function call, you could shorten these three lines:

r = random.randint(1, 9)
fortune = getAnswer(r)
print(fortune)
to this single equivalent line:

print(getAnswer(random.randint(1, 9)))
The None Value
--------------
In Python there is a value called None, which represents the absence of a value. None is the only value of the NoneType data type.
To see this in action, enter the following into the interactive shell:

>>> spam = print('Hello!')
Hello!
>>> None == spam
True
Keyword Arguments and print()
-----------------------------
If you ran the following program:

print('Hello')
print('World')
the output would look like this:

Hello
World
For example, if the program were this:

print('Hello', end='')
print('World')
the output would look like this:

HelloWorld
Enter the following into the interactive shell:

>>> print('cats', 'dogs', 'mice')
cats dogs mice
But you could replace the default separating string by passing the sep keyword argument. Enter the following into the interactive shell:

>>> print('cats', 'dogs', 'mice', sep=',')
cats,dogs,mice

Local and Global Scope
----------------------
Parameters and variables that are assigned in a called function are said to exist in that function’s local scope. Variables 
that are assigned outside all functions are said to exist in the global scope. A variable that exists in a local scope is 
called a local variable, while a variable that exists in the global scope is called a global variable. A variable must be 
one or the other; it cannot be both local and global.
Scopes matter for several reasons:
*Code in the global scope cannot use any local variables.
*However, a local scope can access global variables.
*Code in a function’s local scope cannot use variables in any other local scope.
*You can use the same name for different variables if they are in different scopes. That is, there can be a local variable 
named spam and a global variable also named spam.
Local Variables Cannot Be Used in the Global Scope
--------------------------------------------------
Consider this program, which will cause an error when you run it:

def spam():
    eggs = 31337
spam()
print(eggs)
If you run this program, the output will look like this:

Traceback (most recent call last):
  File "C:/test3784.py", line 4, in <module>
    print(eggs)
NameError: name 'eggs' is not defined
Local Scopes Cannot Use Variables in Other Local Scopes
--------------------------------------------------------
A new local scope is created whenever a function is called, including when a function is called from another function. Consider this program:

  def spam():
➊    eggs = 99
➋    bacon()
➌    print(eggs)

  def bacon():
      ham = 101
➍    eggs = 0

➎ spam()

When the program starts, the spam() function is called ➎, and a local scope is created. The local variable eggs ➊ is set to 
99. Then the bacon() function is called ➋, and a second local scope is created. Multiple local scopes can exist at the same 
time. In this new local scope, the local variable ham is set to 101, and a local variable eggs—which is different from the one
in spam()’s local scope—is also created ➍ and set to 0. When bacon() returns, the local scope for that call is destroyed. The 
program execution continues in the spam() function to print the value of eggs ➌, and since the local scope for the call to 
spam() still exists here, the eggs variable is set to 99. This is what the program prints.
Global Variables Can Be Read from a Local Scope
-----------------------------------------------
Consider the following program:

def spam():
    print(eggs)
eggs = 42
spam()
print(eggs)
This is why 42 is printed when the previous program is run.
Local and Global Variables with the Same Name
---------------------------------------------
 To see what happens, type the following code into the file editor and save it as sameName.py:

   def spam():
➊     eggs = 'spam local'
       print(eggs) # prints 'spam local'
   def bacon():

➋     eggs = 'bacon local'
       print(eggs) # prints 'bacon local'
       spam()
       print(eggs) # prints 'bacon local'

➌ eggs = 'global'
   bacon()
   print(eggs) # prints 'global'
When you run this program, it outputs the following:

bacon local
spam local
bacon local
global
The global Statement
--------------------
 For example, type the following code into the file editor and save it as sameName2.py:

  def spam():
➊    global eggs
➋    eggs = 'spam'

  eggs = 'global'
  spam()
  print(eggs)
When you run this program, the final print() call will output this:

spam
There are four rules to tell whether a variable is in a local scope or global scope:
1. If a variable is being used in the global scope (that is, outside of all functions), then it is always a global variable.
2. If there is a global statement for that variable in a function, it is a global variable.
3. Otherwise, if the variable is used in an assignment statement in the function, it is a local variable.
4. But if the variable is not used in an assignment statement, it is a global variable.
To get a better feel for these rules, here’s an example program. Type the following code into the file editor and save it as sameName3.py:

  def spam():
➊  global eggs
    eggs = 'spam' # this is the global

  def bacon():
➋  eggs = 'bacon' # this is a local
  def ham():
➌  print(eggs) # this is the global

  eggs = 42 # this is the global
  spam()
  print(eggs)
   If you run sameName3.py, the output will look like this:

spam
If you try to use a local variable in a function before you assign a value to it, as in the following program, Python will 
give you an error. To see this, type the following into the file editor and save it as sameName4.py:

  def spam():
      print(eggs) # ERROR!
➊    eggs = 'spam local'

➋ eggs = 'global'
   spam()
If you run the previous program, it produces an error message.

Traceback (most recent call last):
  File "C:/test3784.py", line 6, in <module>
    spam()
  File "C:/test3784.py", line 2, in spam
    print(eggs) # ERROR!
UnboundLocalError: local variable 'eggs' referenced before assignment
Exception Handling
-----------------
Right now, getting an error, or exception, in your Python program means the entire program will crash. You don’t want this to
happen in real-world programs. Instead, you want the program to detect errors, handle them, and then continue to run.
For example, consider the following program, which has a “divide-by-zero” error. Open a new file editor window and enter the
following code, saving it as zeroDivide.py:

def spam(divideBy):
    return 42 / divideBy

print(spam(2))
print(spam(12))
print(spam(0))
print(spam(1))
We’ve defined a function called spam, given it a parameter, and then printed the value of that function with various parameters
to see what happens. This is the output you get when you run the previous code:

21.0
3.5
Traceback (most recent call last):
  File "C:/zeroDivide.py", line 6, in <module>
    print(spam(0))
  File "C:/zeroDivide.py", line 2, in spam
    return 42 / divideBy
ZeroDivisionError: division by zero
Errors can be handled with try and except statements.
You can put the previous divide-by-zero code in a try clause and have an except clause contain code to handle what happens 
when this error occurs.

def spam(divideBy):
    try:
        return 42 / divideBy
    except ZeroDivisionError:
        print('Error: Invalid argument.')

print(spam(2))
print(spam(12))
print(spam(0))
print(spam(1))
When code in a try clause causes an error, the program execution immediately moves to the code in the except clause. After 
running that code, the execution continues as normal. The output of the previous program is as follows:

21.0
3.5
Error: Invalid argument.
None
42.0
Note that any errors that occur in function calls in a try block will also be caught. Consider the following program, which 
instead has the spam() calls in the try block:

def spam(divideBy):
    return 42 / divideBy

try:
    print(spam(2))
    print(spam(12))
    print(spam(0))
    print(spam(1))
except ZeroDivisionError:
    print('Error: Invalid argument.')
When this program is run, the output looks like this:

21.0
3.5
Error: Invalid argument.
A Short Program: Guess the Number
--------------------------------
When you run this program, the output will look something like this:

I am thinking of a number between 1 and 20.
Take a guess.
10
Your guess is too low.
Take a guess.
15
Your guess is too low.
Take a guess.
17
Your guess is too high.
Take a guess.
16
Good job! You guessed my number in 4 guesses!
Type the following source code into the file editor, and save the file as guessTheNumber.py:

# This is a guess the number game.
import random
secretNumber = random.randint(1, 20)
print('I am thinking of a number between 1 and 20.')

# Ask the player to guess 6 times.
for guessesTaken in range(1, 7):
    print('Take a guess.')
    guess = int(input())

    if guess < secretNumber:
        print('Your guess is too low.')
    elif guess > secretNumber:
        print('Your guess is too high.')
    else:
        break    # This condition is the correct guess!

if guess == secretNumber:
    print('Good job! You guessed my number in ' + str(guessesTaken) + ' guesses!')
else:
    print('Nope. The number I was thinking of was ' + str(secretNumber))
Let’s look at this code line by line, starting at the top.

# This is a guess the number game.
import random
secretNumber = random.randint(1, 20)
